repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Updated version for pre-commit-hooks
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 24.10.0 # Specific version of black
    hooks:
      - id: black
        language_version: python3.13 # Update to your Python version

  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.1 # Specific version of pylint
    hooks:
      - id: pylint
        language_version: python3.13 # Ensure this matches your environment

  - repo: local
    hooks:
      - id: run-tests
        name: Run Unit Tests
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
