repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace # Removes trailing whitespace
      - id: end-of-file-fixer # Ensures files end with a single newline
      - id: check-yaml # Validates the YAML file format

  # Black for code formatting
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.11

  # Pylint for linting Python code
  - repo: https://github.com/PyCQA/pylint
    rev: v2.17.5
    hooks:
      - id: pylint

  # run unit tests before committing
  - repo: local
    hooks:
      - id: run-tests
        name: Run Unit Tests
        entry: pytest # Command to run (pytest in this case)
        language: system
        pass_filenames: false
        always_run: true
