repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.1
    hooks:
      - id: pylint
        language_version: python3.11
        additional_dependencies:
          - requests
          - psycopg2
          - python-dotenv
          - pytz
          - pytest
          - signalrcore
        env:
          PYTHONPATH: "."
        entry: bash -c 'PYTHONPATH=. pylint "$@"' _ # Set PYTHONPATH here for pre-commit

  - repo: local
    hooks:
      - id: run-unit-tests
        name: Run Unit Tests
        entry: pytest tests/unit_tests
        language: system
        pass_filenames: false
        always_run: true

      - id: run-integration-tests
        name: Run Integration Tests
        entry: pytest tests/integration_tests
        language: system
        pass_filenames: false
        always_run: true
